USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE OR REPLACE TABLE GOLD.SALES_BY_STATE AS
SELECT
  d.state,
  SUM(f.sales_price) AS total_sales
FROM SILVER.FACT_SALES f
JOIN SILVER.CUSTOMER_DIM d
 ON f.customer_sk = d.customer_sk
GROUP BY d.state; 

SELECT * FROM SILVER.CUSTOMER_DIM;

SELECT * FROM SILVER.FACT_SALES;

---SALES BY YEAR

CREATE OR REPLACE TABLE GOLD.SALES_BY_YEAR AS
SELECT
  YEAR(transaction_date) AS sales_year,
  SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY sales_year;

--SALES BY STORE EVERY MONTH

CREATE OR REPLACE TABLE GOLD.MONTHLY_SALES AS
SELECT
     DATE_TRUNC('month',transaction_date) AS sales_month,
     SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY sales_month;




---TOP 10 STORES BY SALES

CREATE OR REPLACE TABLE GOLD.TOP_STORES AS
SELECT
     store_id,
     SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY store_id
ORDER BY total_sales DESC
LIMIT 10;

---validation

SELECT COUNT(*) FROM GOLD.SALES_BY_STATE;
SELECT COUNT(*) FROM GOLD.SALES_BY_YEAR;
SELECT COUNT(*) FROM GOLD.MONTHLY_SALES;
SELECT COUNT(*) FROM GOLD.TOP_STORES;
SELECT * FROM SILVER.FACT_SALES;
SELECT
   YEAR(transaction_date),
   COUNT(*)
FROM SILVER.FACT_SALES
GROUP BY 1;

SELECT MIN(transaction_date),MAX(transaction_date)
FROM SILVER.FACT_SALES;

ALTER TABLE SILVER.FACT_SALES
CLUSTER BY (transaction_date);


--performance validation
SELECT SUM(sales_price) FROM SILVER.FACT_SALES;
SELECT SUM(total_sales) FROM GOLD.SALES_BY_STATE;

